version: "3.8"

services:
    backend:
        build: .
        ports:
            - 5000:5000
        environment:
            - DB_URL=mongodb://database/vending
            - CACHE_URL=redis://cache
        volumes:
            - .:/app
        depends_on:
            - database
            - cache
        command: ["sh", "docker-dev.sh"]

    database:
        image: mongo:6.0-jammy
        ports: 
            - 27018:27017
        volumes:
            - vending_db:/data/db

    cache:
        image: redis:7.0-alpine3.17
        ports:
            - '6378:6379'
        volumes:
            - vending_cache:/data

volumes:
    vending_db:
    vending_cache:
